# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c3094987e42a880959bf8089f5f77b06226ac358dc6eb7290665ba1f0642d35be0f509a2c1687dbf37b2eed5bbfb3f545523115f06b2bb7a0b01c81d80cbed3

test:
  secret_key_base: ccffd85fb826c5e5d36b9ea6929901a0af7184d3d05ad03a75240643809905e7af20928f655c3f1a378868efe741f46275ad712bcb4b20e27e4307ac72141449

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
