# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9032fdee8cae2475372ecadf35d9b93f730e6b11218138d2192315bcdd27540d2f34e58245557d15c688bed591174b51c7928aa217b015c84568bf7406d90573

test:
  secret_key_base: a36a7f577b5b2b1896e6586a5b8f3eacc2ad8611fc69de90014cd984c79e08f4488e7a717fdf59a31d9d12eb6ffeea580eabf8ae7807b37effa91905b00505af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
